# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ce7e35f8f4687cd20e5d326e6880972cdadfa91ac69d21fe8162da28e2c401323fe02de9cabb8b72392f8002f96255cf6df722b8c81e7371a38c99df004654c

test:
  secret_key_base: b5efe795802b5cbdff7e95799e422ae2cd4af095783a3a0e0276c599b40d1be5c1ebe431465f8596a5af5beb8fc0014c384a308e591b45ff73106ff330ca6323

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
